- name: threetier
  hosts: all
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present
      when: inventory_hostname in groups['webtier']

    - name: install php
      apt: name=php state=present
      when: inventory_hostname in groups ['apptier']

    - name: install database
      apt: name=mariadb-server state=present
      when: inventory_hostname in groups['dbtier']
