- name: installing LEMP
  hosts: myserver
  become: true
  tasks:
     - name: update all packages
       apt:
        name: '*'
        state: latest
 
     - name: installing nginx
       apt: name=nginx state=present
 
     - name: starting nginx
       service: name=nginx state=started
 
     - name: installing php
       apt:
        name: php8.3
        state: present
 
     - name: installing php-fpm
       apt:
        name: php8.3-fpm
        state: present
 
     - name: starting php8.3-fpm
       service:
        name: php8.3-fpm
        state: started
        enabled: true
 
     - name: installing mysql
       apt:
        name: mariadb-server
        state: present
 
     - name: starting mysql
       service:
        name: mariadb
        state: started
        enabled: true

     - name: restart nginx
       service:
        name: nginx
        state: restarted
 
     - name: restart php
       service:
        name: php8.3-fpm
        state: restarted
 
     - name: restart mysql
       service:
        name: mariadb
        state: restarted
