- name: installing LEMP
  hosts: myserver
  become: true
  tasks:
     - name: update all packages
       yum:
        name: '*'
        state: latest
       when: ansible_distribution== 'Amazon'
 
     - name: update all packages
       apt:
        name: '*'
        state: latest
       when: ansible_distribution== 'ubuntu'
 
     - name: installing nginx
       apt:
         name: ['nginx','php8.3', 'php8.3-fpm', 'mariadb-server']
         state: present
       when: ansible_distribution== 'ubuntu'
 
     - name: installing nginx
       yum:
         name: ['nginx','php8.3', 'php8.3-fpm', 'mariadb105-server']
         state: present
       when: ansible_distribution== 'Amazon'
 
     - name: start nginx
       service:
        name: nginx
        state: started
 
     - name: start mysql
       service:
        name: mariadb
        state: started
